name: CI

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Install deps
      run: ./install-ubuntu-prereq.sh
    - name: Build
      run: source last.refs && ./build-kvx-xgcc.sh test-build
