name: CI LLVM

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install deps
      run: ./install-ubuntu-prereq.sh

    - name: Build
      run: source last.refs && ./build-kvx-llvm.sh test-llvm-build
